// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViclesStatus.Models.DBContext;

namespace ViclesStatus.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ViclesStatus.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer_ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Customer_ID = 1,
                            Address = "Nasr City",
                            CustomerName = "customer1"
                        },
                        new
                        {
                            Customer_ID = 2,
                            Address = "maady",
                            CustomerName = "customer2"
                        },
                        new
                        {
                            Customer_ID = 3,
                            Address = "fifth sittlement",
                            CustomerName = "customer3"
                        });
                });

            modelBuilder.Entity("ViclesStatus.Models.Entities.Vehicle", b =>
                {
                    b.Property<int>("Vehicle_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<string>("RegNr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vehicle_ID");

                    b.HasIndex("Customer_ID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Vehicle_ID = 1,
                            Customer_ID = 1,
                            RegNr = "hsdgdt1245"
                        },
                        new
                        {
                            Vehicle_ID = 2,
                            Customer_ID = 2,
                            RegNr = "hhiuie3565"
                        },
                        new
                        {
                            Vehicle_ID = 3,
                            Customer_ID = 3,
                            RegNr = "llddldl65487"
                        });
                });

            modelBuilder.Entity("ViclesStatus.Models.Entities.Vehicle", b =>
                {
                    b.HasOne("ViclesStatus.Models.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("Customer_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ViclesStatus.Models.Entities.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
